FROM tianon/debian:sid
ENV DEBIAN_FRONTEND noninteractive
RUN echo "deb http://packages.linuxmint.com debian import" >> /etc/apt/sources.list
RUN apt-get -y update
RUN apt-get install --force-yes -y -q python python-setuptools libyaml-dev libpq-dev python-dev libpcap-dev net-tools openjdk-7-jre firefox xvfb graphviz python-yara


RUN mkdir -p /opt/fjospidie
ADD fjospidie/ /opt/fjospidie/fjospidie
#ADD firefox/ /opt/fjospidie/firefox
ADD fjospidie.py /opt/fjospidie/
ADD lib/ /opt/fjospidie/lib
ADD ez_setup.py /opt/fjospidie/
ADD fjospidie.conf /opt/fjospidie/
ADD run.sh /opt/fjospidie/
ADD lib/browsermob/userAgentString.txt /tmp/
ADD lib/browsermob/userAgentString.properties /tmp/
ADD yara/ /opt/fjospidie/yara

RUN python /opt/fjospidie/ez_setup.py install
ENV RUNNABLE_USER_DIR /opt/fjospidie
